name: Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: List Xcodes
        run: ls /Applications | grep "Xcode"
      - name: Select Xcode 13.3 beta3
        run: sudo xcode-select -s /Applications/Xcode_13.3-beta3.app
      - name: System
        run: system_profiler SPHardwareDataType
      - name: Run make docs
        run: make docs
